### ISSUE TITLE
一些注音错误

### ISSUE THREAD

**Issue by gumblex** [mozillazg/phrase-pinyin-data#18]
添加：
时长 shí cháng

错误：
'干么': [['gàn'], ['mǒ']],
'干净利索': [['gàn'], ['jìng'], ['lì'], ['suǒ']],
'干名犯义': [['gàn'], ['míng'], ['fàn'], ['yì']],
'干瞪眼': [['gàn'], ['dèng'], ['yǎn']],
'干电池': [['gàn'], ['diàn'], ['chí']],
'干酵母': [['gàn'], ['jiào'], ['mǔ']],

**Comment by mozillazg** [comment]
@gumblex 感谢反馈！欢迎提交 PR 😄

**Comment by gumblex** [comment]
“长”的默认拼音是 zhǎng 啊，是不是应该调换一下

**Comment by mozillazg** [comment]
@gumblex 说的是这里吗？https://github.com/mozillazg/pinyin-data/blob/master/kMandarin_8105.txt#L7105 如果确认最常用拼音是 `cháng` 的话可以换成 `cháng`

**Comment by gumblex** [comment]
感觉上是，一般字典都把 cháng 列在前面。
