### ISSUE TITLE
中兴 兴字声调错误

### ISSUE THREAD

**Issue by GWQi** [mozillazg/phrase-pinyin-data#25]
## 运行环境

* 操作系统（Linux/macOS/Windows）：linux
* Python 版本：3.7
* pypinyin 版本：0.35.3

## 问题描述
Style.TONE3 转换中兴拼音将 ‘兴’ 转换为4声，实则1声
中兴 -> zhong1 xing4

## 问题复现步骤
```
import pypinyin
pypinyin.pinyin('中兴', style=pypinyin.Style.TONE3) # [['zhong1'], ['xing4']]
```

**Comment by mozillazg** [comment]
@GWQi 刚发布的最新版 pypinyin 已经是 1 声了，麻烦更新一下版本然后再试试看：

```
pip install pypinyin==0.39.1
```

**Comment by GWQi** [comment]
> @GWQi 刚发布的最新版 pypinyin 已经是 1 声了，麻烦更新一下版本然后再试试看：
> 
> ```
> pip install pypinyin==0.39.1
> ```

好的，谢谢~
