### ISSUE TITLE
“那些”的读音

### ISSUE THREAD

**Issue by yileld** [mozillazg/phrase-pinyin-data#29]
![image](https://user-images.githubusercontent.com/13084050/112816470-0954d680-90b4-11eb-9697-5e8540475cb9.png)

参考的汉典网似乎错了，上边注音neixie，下边释义又是naxie。还是改成naxie好一点吧？

**Comment by mozillazg** [comment]
@yileld 感谢反馈！等我有空的时候看一下，谢谢~

**Comment by yileld** [comment]
又发现一个。。。“谁”的读音是shei2

**Comment by mozillazg** [comment]
@yileld 谁的这个没错，可以看一下这个 https://github.com/mozillazg/python-pinyin/issues/181
