### ISSUE TITLE
「知了」的「了」在一些词典中不是轻声

### ISSUE THREAD

**Issue by AlienKevin** [mozillazg/phrase-pinyin-data#41]
「知了」的「了」在PR https://github.com/mozillazg/phrase-pinyin-data/pull/40 处被从三声改为了轻声，不过各大词典都标注的是三声：
现代汉语规范词典
牛津英汉汉英词典
現代漢語大詞典
五南國語活用辭典

**Comment by mozillazg** [comment]
感谢反馈！

**Comment by AlienKevin** [comment]
我个人是读轻声，就看phrase-pinyin-data项目的宗旨是遵从字典等参考书，还是也会考虑大众的读音？
