### ISSUE TITLE
「便宜」读音是否改为轻声？

### ISSUE THREAD

**Issue by AlienKevin** [mozillazg/phrase-pinyin-data#43]
「便宜」的读音现在记为pián yí，但是《现代汉语规范词典》、《商務新詞典》和《牛津英汉汉英词典》三本词典里都是用的pián yi（还有一个读音biàn yí表示另一个意思）。我自己也是用轻声，身边不少认识人也是读轻声。可否考虑改为轻声？

参考：
《现代汉语规范词典》
<img width="345" alt="Screenshot 2023-01-13 at 10 05 54 AM" src="https://user-images.githubusercontent.com/22850071/212352481-f9d743e7-f445-43dd-ad14-bf4305f84425.png">

《商務新詞典》
<img width="260" alt="Screenshot 2023-01-13 at 10 09 03 AM" src="https://user-images.githubusercontent.com/22850071/212352771-f1067943-c710-4943-ab9c-98de32890c53.png">

《牛津英汉汉英词典》
<img width="351" alt="Screenshot 2023-01-13 at 10 07 03 AM" src="https://user-images.githubusercontent.com/22850071/212352475-e984434e-9e6a-4959-a319-c894233075a9.png">

**Comment by mozillazg** [comment]
@AlienKevin 感谢反馈！
